language : java
install :
    - git clone https://github.com/PFGimenez/The-Kraken-Pathfinding.git --depth 1
    - cd The-Kraken-Pathfinding
    - ./install_dependencies.sh
    - cd core
    - mvn install
    - cd ../..
script :
    - cd high_level
    - ./update.sh
jdk :
    - oraclejdk8
notifications:
    slack: intech-sudparis:Z3xKQEmZT2a9BFBqouokQ6J7
    on_success: change
    on_failure: always
    email : false
branches:
    only : master
